window.QM_CORE=(function(){
const D=window.QM_DATA,U=window.QM_UTILS,C=window.QM_CALENDAR,R=window.QM_RELATIONS;
function getXunInfo(gz){const idx=D.SIXTY.indexOf(gz);if(idx<0)return D.HIDDEN_JIA[0];const start=D.SIXTY[Math.floor(idx/10)*10];return D.HIDDEN_JIA.find(x=>x.start===start)||D.HIDDEN_JIA[0]}
function getXunOffset(gz){const idx=D.SIXTY.indexOf(gz);return idx<0?0:idx%10}
function buildEarthPlate(ju,dun){const terms=['戊','己','庚','辛','壬','癸','丁','丙','乙'],res={};let p=ju;for(const s of terms){res[p]=s;p=dun==='阳遁'?p+1:p-1;if(p>9)p=1;if(p<1)p=9}return res}
function rotateMap(base,order,from,to){const res={},fi=order.indexOf(from),ti=order.indexOf(to),shift=U.mod(ti-fi,order.length);for(let i=0;i<order.length;i++){res[order[U.mod(i+shift,order.length)]]=base[order[i]]}return res}
function normRing(p){return D.RING.includes(p)?p:2}
function normStar(p){return D.STAR_RING.includes(p)?p:5}
function palaceOfStem(plate,stem){const f=Object.entries(plate).find(([p,s])=>s===stem);return f?Number(f[0]):5}
function buildGodPlate(dun,zhifuPalace){const res={},start=normRing(zhifuPalace),si=D.RING.indexOf(start);for(let i=0;i<D.GOD_ORDER.length;i++){const idx=dun==='阳遁'?si+i:si-i;res[D.RING[U.mod(idx,D.RING.length)]]=D.GOD_ORDER[i]}res[5]='中宫寄神';return res}
function horseBranch(br){if(['寅','午','戌'].includes(br))return '申';if(['申','子','辰'].includes(br))return '寅';if(['巳','酉','丑'].includes(br))return '亥';if(['亥','卯','未'].includes(br))return '巳';return '申'}
function palaceByBranch(br){for(const p of Object.values(D.PALACES))if(p.branch.includes(br))return p.num;return {子:1,丑:8,寅:8,卯:3,辰:4,巳:4,午:9,未:2,申:2,酉:7,戌:6,亥:6}[br]||5}
function detectStemPatterns(pair,heaven,earth){const tags=[],good={乙丙:'奇仪顺遂：乙奇见丙，利文书、协作、推进。',乙丁:'玉女类象：乙丁相见，利柔性沟通、方案包装。',丙丁:'火奇相会：信息显明、声势增强，但也防过热。',丁乙:'丁奇见乙：利消息、文书、暗线资源。'},bad={庚乙:'庚乙相逢：金木相战，合作、感情、谈判多压力。',庚丙:'庚丙相制：冲突显化，易有执行阻力。',庚丁:'庚丁相见：压力与消息并见，需防突发变化。',辛乙:'辛乙相克：细节、规则、口舌压制柔性关系。'};if(good[pair])tags.push({type:'good',label:'干格吉象',reason:good[pair]});if(bad[pair])tags.push({type:'bad',label:'干格压力',reason:bad[pair]});if(heaven&&heaven===earth)tags.push({type:'warn',label:'伏吟象',reason:'天盘干与地盘干相同，主重复、迟滞、原地盘旋。'});return tags}
function buildPalace(num,ctx){const palace=D.PALACES[num],door=ctx.doors[num]||null,star=ctx.stars[num]||null,godName=ctx.gods[num]||null,god=godName&&D.GOD_META[godName]?Object.assign({name:godName},D.GOD_META[godName]):godName?{name:godName,nature:'平',desc:'中宫寄托'}:null,earthStem=ctx.earthPlate[num],heavenStem=ctx.heavenPlate[num],tags=[],branches=palace.branch||[],isHourVoid=branches.some(b=>ctx.hourXun.voids.includes(b)),isDayVoid=branches.some(b=>ctx.dayXun.voids.includes(b)),hasHorse=ctx.horsePalace===num;
if(isHourVoid)tags.push({type:'bad',label:'时空亡',reason:`时旬空亡：${ctx.hourXun.voids.join('、')}`});if(isDayVoid)tags.push({type:'warn',label:'日空亡',reason:`日旬空亡：${ctx.dayXun.voids.join('、')}`});if(hasHorse)tags.push({type:'good',label:`马星${ctx.horseBranch}`,reason:`时支驿马落${palace.name}`});if(['乙','丙','丁'].includes(heavenStem))tags.push({type:'good',label:`天盘三奇${heavenStem}`,reason:'乙丙丁为三奇'});if(['庚','辛'].includes(heavenStem))tags.push({type:'warn',label:`天盘${heavenStem}`,reason:'庚辛多主阻隔、压力、制度或冲突'});if(door&&door.nature==='吉')tags.push({type:'good',label:door.name+'吉门',reason:door.desc});if(door&&door.nature==='凶')tags.push({type:'bad',label:door.name+'凶门',reason:door.desc});if(star&&star.name==='天芮')tags.push({type:'bad',label:'天芮病符',reason:'天芮多主病、问题、负担或学习成本'});if(god&&['值符','六合','太阴','九天'].includes(god.name))tags.push({type:'good',label:god.name,reason:god.desc});if(god&&['白虎','玄武','螣蛇'].includes(god.name))tags.push({type:'bad',label:god.name,reason:god.desc});if(door&&R.elementRelation(palace.element,door.element).type==='克')tags.push({type:'bad',label:'门迫',reason:`${palace.element}克${door.element}，门受宫迫`});tags.push(...detectStemPatterns((heavenStem||'')+(earthStem||''),heavenStem,earthStem));return {id:`palace_${num}`,num,name:palace.name,gua:palace.gua,element:palace.element,direction:palace.dir,branches,door,star,god,heavenStem,earthStem,tags,void:{hour:isHourVoid,day:isDayVoid},horse:hasHorse?ctx.horseBranch:null,isZhifuPalace:ctx.zhifuPalace===num,isZhishiPalace:ctx.zhishiPalace===num}}
function buildQimenChart(input){const date=input.date||new Date(),calendar=C.computeCalendar(date),hourXun=getXunInfo(calendar.hourGz),dayXun=getXunInfo(calendar.dayGz),earthPlate=buildEarthPlate(calendar.juNumber,calendar.dun),xunPalace=palaceOfStem(earthPlate,hourXun.hidden),hourStem=calendar.hourGz[0],hourStemPal=palaceOfStem(earthPlate,hourStem),baseStars={};D.STAR_RING.forEach(p=>baseStars[p]=D.BASE_STARS[p]);const stars=rotateMap(baseStars,D.STAR_RING,normStar(xunPalace),hourStemPal),zhifuStar=D.BASE_STARS[normStar(xunPalace)].name,zhifuPalace=Number(Object.keys(stars).find(p=>stars[p].name===zhifuStar))||hourStemPal,xunRing=normRing(xunPalace),offset=getXunOffset(calendar.hourGz),zhishiPalace=D.RING[U.mod(D.RING.indexOf(xunRing)+(calendar.dun==='阳遁'?offset:-offset),D.RING.length)],zhishiDoor=D.BASE_DOORS[xunRing].name,doors=rotateMap(D.BASE_DOORS,D.RING,xunRing,zhishiPalace),gods=buildGodPlate(calendar.dun,zhifuPalace),heavenPlate=rotateMap(earthPlate,D.PALACE_NUMS,palaceOfStem(earthPlate,hourXun.hidden),palaceOfStem(earthPlate,hourStem)),hb=horseBranch(calendar.hourGz[1]),hp=palaceByBranch(hb),ctx={calendar,earthPlate,heavenPlate,doors,stars,gods,hourXun,dayXun,zhifuPalace,zhishiPalace,zhishiDoor,horseBranch:hb,horsePalace:hp};
const raw=D.GRID.map(n=>buildPalace(n,ctx)),edges=R.buildEdges(raw,{calendar,zhifuPalace,zhishiPalace}),modifiers=R.buildModifiers(raw),palaces=raw.map(p=>Object.assign({},p,{metrics:R.calculateMetrics(p,edges,modifiers)})),topic=input.topic||'general',useIndex=R.buildUseIndex(palaces,{calendar,zhifuPalace,zhishiPalace,topic});return {version:'qimen-graph-static-v0.2-structured',createdAt:new Date().toISOString(),input:{datetime:date.toISOString(),localDatetime:U.localInputValue(date),castMode:input.castMode||'hour',school:input.school||'rotating',juMethod:input.juMethod||'sanyuan',topic,topicName:(D.TOPIC_CONFIG[topic]||D.TOPIC_CONFIG.general).name,question:input.question||''},calendar,qimen:{dun:calendar.dun,juNumber:calendar.juNumber,yuan:calendar.yuan,solarTerm:calendar.term,hourXunStart:hourXun.start,xunshouHidden:hourXun.hidden,hourVoids:hourXun.voids,dayXunStart:dayXun.start,dayVoids:dayXun.voids,zhifuStar,zhifuPalace,zhishiDoor,zhishiPalace,horseBranch:hb,horsePalace:hp},plates:{earthPlate,heavenPlate},palaces,edges,modifiers,useIndex,notes:['当前版本为静态前端原型，历法和定局使用近似/产品化取法，后续建议接入严格历法库。','不同奇门流派对拆补、置闰、转盘、飞盘、值符值使排布有差异。','状态量化用于辅助理解关系，不等于最终断语。']}}
return {buildQimenChart};
})();
