window.QM_RELATIONS=(function(){
const D=window.QM_DATA,U=window.QM_UTILS;
function elementRelation(a,b){if(!a||!b)return {type:'未知',delta:0,text:'关系未定'};if(a===b)return {type:'比和',delta:5,text:`${a}${b}比和，气类相同`};if(D.ELEMENT_GENERATES[a]===b)return {type:'生',delta:8,text:`${a}生${b}，前者助后者`};if(D.ELEMENT_GENERATES[b]===a)return {type:'泄',delta:-2,text:`${b}生${a}，后者被前者泄气`};if(D.ELEMENT_CONTROLS[a]===b)return {type:'克',delta:-9,text:`${a}克${b}，前者制后者`};if(D.ELEMENT_CONTROLS[b]===a)return {type:'受克',delta:-8,text:`${b}克${a}，前者受制`};return {type:'平',delta:0,text:'无直接生克'}}
function godDelta(name){if(['值符','太阴','六合','九天'].includes(name))return 10;if(name==='九地')return 4;if(['螣蛇','白虎','玄武'].includes(name))return -9;return 0}
function findStemPalace(palaces,stem){return palaces.find(p=>p.heavenStem===stem)||palaces.find(p=>p.earthStem===stem)}
function opposite(n){return {1:9,9:1,3:7,7:3,4:6,6:4,2:8,8:2}[n]||null}
function buildEdges(palaces,ctx){const edges=[];for(const p of palaces){if(p.door){const r=elementRelation(p.door.element,p.element);edges.push({id:`edge_door_${p.num}`,source:`${p.door.name}(${p.door.element})`,target:p.name,sourceId:`door_${p.num}`,targetId:p.id,type:`门宫${r.type}`,dimension:'门用',weight:r.delta,reason:`${p.door.name}属${p.door.element}，${p.name}属${p.element}：${r.text}。${p.door.desc}。`})}if(p.star){const r=elementRelation(p.star.element,p.element);edges.push({id:`edge_star_${p.num}`,source:`${p.star.name}(${p.star.element})`,target:p.name,sourceId:`star_${p.num}`,targetId:p.id,type:`星宫${r.type}`,dimension:'星势',weight:r.delta,reason:`${p.star.name}属${p.star.element}，${p.name}属${p.element}：${r.text}。${p.star.desc}。`})}if(p.god){edges.push({id:`edge_god_${p.num}`,source:p.god.name,target:p.name,sourceId:`god_${p.num}`,targetId:p.id,type:'神盘作用',dimension:'神助',weight:godDelta(p.god.name),reason:`${p.god.name}：${p.god.desc||'中宫寄神'}。`})}if(p.heavenStem&&p.earthStem){const r=elementRelation(D.STEM_ELEMENT[p.heavenStem],D.STEM_ELEMENT[p.earthStem]);edges.push({id:`edge_stem_${p.num}`,source:`天盘${p.heavenStem}`,target:`地盘${p.earthStem}`,sourceId:`heaven_${p.num}`,targetId:`earth_${p.num}`,palaceId:p.id,type:`干干${r.type}`,dimension:'格局',weight:r.delta,reason:`天盘${p.heavenStem}属${D.STEM_ELEMENT[p.heavenStem]}，地盘${p.earthStem}属${D.STEM_ELEMENT[p.earthStem]}：${r.text}。`})}}
const dayStem=ctx.calendar.dayGz[0],hourStem=ctx.calendar.hourGz[0],dayPal=findStemPalace(palaces,dayStem),hourPal=findStemPalace(palaces,hourStem);if(dayPal&&hourPal){const r=elementRelation(dayPal.element,hourPal.element);edges.push({id:'edge_day_hour',source:`日干${dayStem} / ${dayPal.name}`,target:`时干${hourStem} / ${hourPal.name}`,sourceId:dayPal.id,targetId:hourPal.id,type:`日时${r.type}`,dimension:'用神',weight:r.delta,reason:`日干常取主体，时干常取事体、对方或当下结果。${dayPal.name}属${dayPal.element}，${hourPal.name}属${hourPal.element}：${r.text}。`})}
const zf=palaces.find(p=>p.num===ctx.zhifuPalace),zs=palaces.find(p=>p.num===ctx.zhishiPalace);if(zf&&zs){const r=elementRelation(zf.element,zs.element);edges.push({id:'edge_zhifu_zhishi',source:`值符 / ${zf.name}`,target:`值使 / ${zs.name}`,sourceId:zf.id,targetId:zs.id,type:`符使${r.type}`,dimension:'主控执行',weight:r.delta,reason:`值符主全局主控，值使主执行路径。${zf.name}与${zs.name}：${r.text}。`})}
for(const p of palaces){const op=palaces.find(x=>x.num===opposite(p.num));if(op&&p.num<op.num)edges.push({id:`edge_opposite_${p.num}_${op.num}`,source:p.name,target:op.name,sourceId:p.id,targetId:op.id,type:'对冲宫',dimension:'宫间',weight:-6,reason:`${p.name}与${op.name}为对宫，主对立、牵扯、远近相照。`})}return edges}
function buildModifiers(palaces){const mods=[];for(const p of palaces){if(p.void.hour)mods.push({id:`mod_hour_void_${p.num}`,target:p.id,targetName:p.name,dimension:'落地',type:'时空亡',delta:-26,reason:`${p.name}命中时旬空亡，象有而力虚，落地感下降。`});if(p.void.day)mods.push({id:`mod_day_void_${p.num}`,target:p.id,targetName:p.name,dimension:'落地',type:'日空亡',delta:-14,reason:`${p.name}命中日旬空亡，现实凭据不足或当前不实。`});if(p.horse)mods.push({id:`mod_horse_${p.num}`,target:p.id,targetName:p.name,dimension:'落地',type:'马星',delta:9,reason:`驿马${p.horse}落${p.name}，主动、移动、变化、奔波。`});if(p.door&&elementRelation(p.element,p.door.element).type==='克')mods.push({id:`mod_door_pressure_${p.num}`,target:p.id,targetName:p.name,dimension:'门用',type:'门迫',delta:-18,reason:`宫五行${p.element}克门五行${p.door.element}，${p.door.name}受迫，可用性下降。`});for(const t of p.tags){if(t.label==='干格吉象')mods.push({id:`mod_good_pattern_${p.num}`,target:p.id,targetName:p.name,dimension:'格局',type:'吉格提示',delta:12,reason:t.reason});if(t.label==='干格压力')mods.push({id:`mod_bad_pattern_${p.num}`,target:p.id,targetName:p.name,dimension:'格局',type:'凶格压力',delta:-14,reason:t.reason});if(t.label==='伏吟象')mods.push({id:`mod_fuyin_${p.num}`,target:p.id,targetName:p.name,dimension:'落地',type:'伏吟',delta:-10,reason:t.reason})}if(p.isZhifuPalace)mods.push({id:`mod_zhifu_${p.num}`,target:p.id,targetName:p.name,dimension:'神助',type:'值符临宫',delta:10,reason:`值符主全局主控与高层资源，临${p.name}，该宫成为枢纽。`});if(p.isZhishiPalace)mods.push({id:`mod_zhishi_${p.num}`,target:p.id,targetName:p.name,dimension:'门用',type:'值使临宫',delta:8,reason:`值使主执行路径与事务入口，临${p.name}，该宫关系到事情如何推进。`})}return mods}
function calculateMetrics(p,edges,mods){const incoming=edges.filter(e=>e.targetId===p.id||e.palaceId===p.id),ms=mods.filter(m=>m.target===p.id),d={宫势:50,门用:50,星势:50,神助:50,格局:50,落地:50};if(p.door)d.门用+=p.door.nature==='吉'?18:p.door.nature==='凶'?-14:4;if(p.star)d.星势+=p.star.nature==='吉'?14:p.star.nature==='凶'?-10:4;if(p.god)d.神助+=godDelta(p.god.name);if(['乙','丙','丁'].includes(p.heavenStem))d.格局+=10;if(['庚','辛'].includes(p.heavenStem))d.格局-=4;for(const e of incoming){if(d[e.dimension]!=null)d[e.dimension]+=e.weight;else d.宫势+=e.weight}for(const m of ms){if(d[m.dimension]!=null)d[m.dimension]+=m.delta;else d.宫势+=m.delta}Object.keys(d).forEach(k=>d[k]=U.clamp(d[k]));d.综合=Math.round((d.宫势+d.门用+d.星势+d.神助+d.格局+d.落地)/6);return d}
function buildUseIndex(palaces,ctx){const topic=D.TOPIC_CONFIG[ctx.topic]||D.TOPIC_CONFIG.general,items=[];function add(label,p,reason){if(p)items.push({label,palaceNum:p.num,palaceName:p.name,score:p.metrics?p.metrics.综合:null,reason})}const ds=ctx.calendar.dayGz[0],hs=ctx.calendar.hourGz[0];add(`日干${ds}`,findStemPalace(palaces,ds),'日干常代表主体、我方、占问者。');add(`时干${hs}`,findStemPalace(palaces,hs),'时干常代表事体、对方、当下结果或外部响应。');add('值符',palaces.find(p=>p.num===ctx.zhifuPalace),'值符代表全局主控、资源、权柄与核心态势。');add('值使',palaces.find(p=>p.num===ctx.zhishiPalace),'值使代表执行路径、事务入口与落地门。');if(ctx.topic==='wealth')add('生门',palaces.find(p=>p.door&&p.door.name==='生门'),'求财、收益、资源增长常看生门。');if(ctx.topic==='career')add('开门',palaces.find(p=>p.door&&p.door.name==='开门'),'事业、项目、机会、开放路径常看开门。');if(ctx.topic==='love'){add('乙奇',findStemPalace(palaces,'乙'),'乙常作柔性关系、女方或关系中的柔性因素。');add('庚仪',findStemPalace(palaces,'庚'),'庚常作男方、阻隔、压力或强硬因素。');add('六合',palaces.find(p=>p.god&&p.god.name==='六合'),'六合主关系、合作、契约、和合。')}if(ctx.topic==='health'){add('天芮',palaces.find(p=>p.star&&p.star.name==='天芮'),'天芮多主疾病、问题、负担。');add('死门',palaces.find(p=>p.door&&p.door.name==='死门'),'健康疾病问事常参考死门与病符。')}if(ctx.topic==='travel'){add('马星',palaces.find(p=>p.horse),'马星主动、行走、迁移、变化。');add('开门',palaces.find(p=>p.door&&p.door.name==='开门'),'出行行动看路径是否开通。')}if(ctx.topic==='exam'){add('景门',palaces.find(p=>p.door&&p.door.name==='景门'),'景门主文书、表达、曝光、考试呈现。');add('天辅',palaces.find(p=>p.star&&p.star.name==='天辅'),'天辅主学习、辅助、文教。');add('丁奇',findStemPalace(palaces,'丁'),'丁奇主文书、消息、灵感、细节。')}return {topic:topic.name,note:topic.note,items}}
return {elementRelation,godDelta,buildEdges,buildModifiers,calculateMetrics,buildUseIndex,findStemPalace};
})();
