window.QM_RENDER=(function(){
const D=window.QM_DATA,U=window.QM_UTILS;
function renderChrome(chart){document.getElementById('heroJu').textContent=`${chart.qimen.dun}${chart.qimen.juNumber}局`;document.getElementById('heroExplain').textContent=`${chart.calendar.term} ${chart.calendar.yuan}｜${chart.calendar.yearGz}年 ${chart.calendar.monthGz}月 ${chart.calendar.dayGz}日 ${chart.calendar.hourGz}时｜旬首${chart.qimen.hourXunStart}遁${chart.qimen.xunshouHidden}`}
function renderSummary(chart){const data=[['四柱',`${chart.calendar.yearGz} ${chart.calendar.monthGz} ${chart.calendar.dayGz} ${chart.calendar.hourGz}`,chart.calendar.fromLunar?'lunar-javascript / 严格换算优先':'内置近似算法'],['节气三元',`${chart.calendar.term} / ${chart.calendar.yuan}`,`阴阳遁：${chart.qimen.dun}`],['局式',`${chart.qimen.dun}${chart.qimen.juNumber}局`,`旬首${chart.qimen.hourXunStart}，甲遁${chart.qimen.xunshouHidden}`],['符使',`值符${chart.qimen.zhifuStar} / 值使${chart.qimen.zhishiDoor}`,`符在${D.PALACES[chart.qimen.zhifuPalace].name}，使在${D.PALACES[chart.qimen.zhishiPalace].name}`]];document.getElementById('summary').innerHTML=data.map(([k,v,s])=>`<div class="summary-card"><div class="k">${U.escapeHtml(k)}</div><div class="v">${U.escapeHtml(v)}</div><div class="s">${U.escapeHtml(s)}</div></div>`).join('')}
function layer(label,value,explain){return `<div class="layer"><div class="label">${U.escapeHtml(label)}</div><div class="value">${U.escapeHtml(value)}</div><div class="explain">${U.escapeHtml(explain)}</div></div>`}
function renderPalaceCard(p,sel){const active=sel===p.num?' active':'',scoreClass=p.metrics.综合>=68?'score-good':p.metrics.综合<=42?'score-bad':'score-mid',tags=p.tags.slice(0,7).map(t=>`<span class="tag ${t.type}">${U.escapeHtml(t.label)}</span>`).join(''),metrics=['宫势','门用','星势','神助','格局','落地'].map(k=>`<div class="metric"><div class="metric-name"><span>${k}</span><span>${Math.round(p.metrics[k])}</span></div><div class="bar"><div class="fill" style="width:${U.clamp(p.metrics[k])}%"></div></div></div>`).join('');return `<article class="palace${active}" data-num="${p.num}"><div class="palace-head"><div><div class="palace-name">${U.escapeHtml(p.name)}</div><div class="palace-sub">${U.escapeHtml(p.direction)}｜${U.escapeHtml(p.gua)}卦｜${U.escapeHtml(p.element)}｜${p.branches.join('、')||'中'}</div></div><div class="score-pill ${scoreClass}">综合 ${p.metrics.综合}</div></div><div class="layers">${layer('神',p.god?p.god.name:'—',p.god?p.god.nature:'')}${layer('星',p.star?p.star.name:'—',p.star?p.star.nature:'')}${layer('门',p.door?p.door.name:'—',p.door?p.door.nature:'')}${layer('天干',p.heavenStem||'—',p.heavenStem?D.STEM_ELEMENT[p.heavenStem]:'')}${layer('地干',p.earthStem||'—',p.earthStem?D.STEM_ELEMENT[p.earthStem]:'')}</div><div class="tags">${tags||'<span class="tag">无显著标签</span>'}</div><div class="metrics">${metrics}</div></article>`}
function renderBoard(chart,sel,onSelect){const board=document.getElementById('board');board.innerHTML=chart.palaces.map(p=>renderPalaceCard(p,sel)).join('');board.querySelectorAll('.palace').forEach(el=>el.addEventListener('click',()=>onSelect(Number(el.dataset.num))))}
function kv(k,v){return `<div class="kv"><div class="key">${U.escapeHtml(k)}</div><div>${U.escapeHtml(v)}</div></div>`}
function edgeHtml(e){const cls=e.weight>0?'delta-pos':e.weight<0?'delta-neg':'delta-zero';return `<div class="edge"><div class="path">${U.escapeHtml(e.source)} → ${U.escapeHtml(e.type)} → ${U.escapeHtml(e.target)} <span class="${cls}">${e.weight>0?'+':''}${e.weight}</span></div><div class="why">${U.escapeHtml(e.reason)}</div></div>`}
function modHtml(m){const cls=m.delta>0?'delta-pos':m.delta<0?'delta-neg':'delta-zero';return `<div class="mod"><div class="path">${U.escapeHtml(m.type)}｜${U.escapeHtml(m.dimension)} <span class="${cls}">${m.delta>0?'+':''}${m.delta}</span></div><div class="why">${U.escapeHtml(m.reason)}</div></div>`}
function svgGraph(p){const nodes=[{id:'center',label:p.name,x:190,y:115,main:true},{id:'door',label:p.door?p.door.name:'门',x:70,y:50},{id:'star',label:p.star?p.star.name:'星',x:310,y:50},{id:'god',label:p.god?p.god.name:'神',x:70,y:180},{id:'stem',label:`${p.heavenStem||'天'} / ${p.earthStem||'地'}`,x:310,y:180}],lines=[['door','center'],['star','center'],['god','center'],['stem','center']];return `<svg viewBox="0 0 380 230" width="100%" height="100%"><defs><marker id="arrow" markerWidth="8" markerHeight="8" refX="5" refY="3" orient="auto"><path d="M0,0 L0,6 L6,3 z" fill="rgba(203,213,225,.72)"></path></marker></defs>${lines.map(([a,b])=>{const A=nodes.find(n=>n.id===a),B=nodes.find(n=>n.id===b);return `<line x1="${A.x}" y1="${A.y}" x2="${B.x}" y2="${B.y}" stroke="rgba(203,213,225,.45)" stroke-width="1.4" marker-end="url(#arrow)"></line>`}).join('')}${nodes.map(n=>`<g><circle cx="${n.x}" cy="${n.y}" r="${n.main?34:27}" fill="${n.main?'rgba(251,191,36,.22)':'rgba(15,23,42,.9)'}" stroke="${n.main?'rgba(251,191,36,.85)':'rgba(148,163,184,.5)'}" stroke-width="1.5"></circle><text x="${n.x}" y="${n.y+4}" text-anchor="middle" fill="#e5e7eb" font-size="${n.main?13:12}" font-weight="700">${U.escapeSvg(n.label)}</text></g>`).join('')}</svg>`}
function renderDetail(chart,num,onCopy){const p=chart.palaces.find(x=>x.num===num);if(!p)return;const edges=chart.edges.filter(e=>e.targetId===p.id||e.sourceId===p.id||e.palaceId===p.id||e.sourceId===`door_${p.num}`||e.sourceId===`star_${p.num}`||e.sourceId===`god_${p.num}`||e.sourceId===`heaven_${p.num}`||e.targetId===`earth_${p.num}`),mods=chart.modifiers.filter(m=>m.target===p.id),hits=chart.useIndex.items.filter(i=>i.palaceNum===p.num);document.getElementById('detail').innerHTML=`<div class="detail-title"><div><h2>${U.escapeHtml(p.name)}详情</h2><div class="small-note">${U.escapeHtml(p.direction)}｜${U.escapeHtml(p.gua)}｜${U.escapeHtml(p.element)}｜综合 ${p.metrics.综合}</div></div><button class="btn" id="copyPalaceBtn">复制本宫</button></div><div class="section"><h3>本宫要素</h3>${kv('宫位',`${p.name}，${p.direction}，${p.element}`)}${kv('八门',p.door?`${p.door.name}（${p.door.element}，${p.door.nature}）：${p.door.desc}`:'—')}${kv('九星',p.star?`${p.star.name}（${p.star.element}，${p.star.nature}）：${p.star.desc}`:'—')}${kv('八神',p.god?`${p.god.name}（${p.god.nature}）：${p.god.desc}`:'—')}${kv('天盘/地盘',`天盘${p.heavenStem||'—'} / 地盘${p.earthStem||'—'}`)}${kv('特殊标签',p.tags.map(t=>t.label).join('、')||'无')}</div><div class="section"><h3>用神命中</h3>${hits.length?hits.map(i=>`<div class="mod"><div class="path">${U.escapeHtml(i.label)} 命中本宫</div><div class="why">${U.escapeHtml(i.reason)}</div></div>`).join(''):'<div class="hint-box">当前取用模板未直接命中本宫。</div>'}</div><div class="section"><h3>六维量化</h3>${Object.entries(p.metrics).map(([k,v])=>kv(k,`${Math.round(v)} / 100`)).join('')}</div><div class="section"><h3>局部关系边图</h3><div class="graph">${svgGraph(p)}</div></div><div class="section"><h3>关系边</h3>${edges.length?edges.map(edgeHtml).join(''):'<div class="hint-box">暂无关系边。</div>'}</div><div class="section"><h3>状态修正项</h3>${mods.length?mods.map(modHtml).join(''):'<div class="hint-box">暂无修正项。</div>'}</div>`;document.getElementById('copyPalaceBtn').addEventListener('click',()=>onCopy(p,edges,mods))}
return {renderChrome,renderSummary,renderBoard,renderDetail};
})();
